export default {
  GET_BALANCE: 'GET_BALANCE',
  UPDATE_BALANCE: 'UPDATE_BALANCE',
  ADD_INCOME_EXPENSE_DATA: 'ADD_INCOME_EXPENSE_DATA',
  EDIT_INCOME_EXPENSE_DATA: 'EDIT_INCOME_EXPENSE_DATA',
  CHANGE_MODAL_VIEW: 'CHANGE_MODAL_VIEW',
};
